name: Node.js CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./web/package-lock.json
    - name: Install dependencies
      working-directory: ./web
      run: npm ci --force
    - name: build frontend
      working-directory: ./web
      run: npm run build
    - name: run test
      working-directory: ./web
      run: npm test

  build-and-deploy:
    needs: [test]
    runs-on: self-hosted
      #strategy:
      #  matrix:
      #    node-version: [12.x, 14.x, 16.x]
    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      #- name: Use Node.js ${{ matrix.node-version }}
      # uses: actions/setup-node@v3
        #with:
         # node-version: ${{ matrix.node-version }}
          #cache: 'npm'
          #cache-dependency-path: web/package-lock.json
      - name: Image prune
        run: sudo docker image prune -f
      - name: docker build
        run: sudo docker-compose build frontend
      - name: docker-compose up
        run: sudo docker-compose up -d frontend
